esphome:
  name: nilan
  platform: ESP8266
  board: d1_mini

external_components:
  - source: components
    components: [nilan_cts602]
wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password

logger:

mqtt:
  broker: !secret mqtt_broker
  username: !secret mqtt_username
  password: !secret mqtt_password

web_server:
  port: 80

# RS485 UART Configuration
uart:
  id: uart_bus
  tx_pin:
    number: GPIO1
    inverted: false
  rx_pin:
    number: GPIO3
    inverted: false
  baud_rate: 19200
  stop_bits: 1
  parity: NONE

# Load Custom Component
nilan_cts602:
  id: nilan_controller
  uart_id: uart_bus
